spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    url: jdbc:mysql://120.78.153.4:3306/mydb?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell